### PR TITLE
Add support for refund with WooCommerce default form

### PR DESCRIPTION
**Pull request by shahbaz-mehar**

### CODE REVIEW

**Review by BushraAsif — COMMENTED** [review]
Changes reviewed

**Comment by emicha** [comment]
@shahbaz-mehar Changes look fine, but tests are failing:

https://github.com/AltaPay/plugin-wordpress/runs/7211857870?check_suite_focus=true

Could you check why? This could be a configuration change in Klarna that has changed how components are being rendered.

**Comment by shahbaz-mehar** [comment]
> @shahbaz-mehar Changes look fine, but tests are failing:
> 
> https://github.com/AltaPay/plugin-wordpress/runs/7211857870?check_suite_focus=true
> 
> Could you check why? This could be a configuration change in Klarna that has changed how components are being rendered.

@emicha Klarna tests are failing because klarna form is not loading properly during cypress tests. We are looking into it.

**Comment by shahbaz-mehar** [comment]
> @shahbaz-mehar Changes look fine, but tests are failing:
> 
> https://github.com/AltaPay/plugin-wordpress/runs/7211857870?check_suite_focus=true
> 
> Could you check why? This could be a configuration change in Klarna that has changed how components are being rendered.

@emicha Issue has been fixed now.

**Review by emicha — APPROVED** [review]

**Pull request merged**
